[package]
name = "price-oracle-canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.17.2"
ic-cdk-macros = "0.18.2"
futures = "0.3"

candid = "0.10.14"
serde = { version = "1.0", features = ["derive"] }





